### ISSUE TITLE
Styling search bar

### ISSUE THREAD

**Issue by MenoIy** [MenoIy/Pokedex-react-ts#1]
Currently the search bar have no style
```
      <input
        type="text"
        placeholder="Search"
        value={toSearch}
        onChange={handelChange}
      />
```

[] Add className for the input 
[] Add css to App.css

**Comment by ghousahmed** [comment]
I'm working on this. 
please assign

**Comment by MenoIy** [comment]
sorry @ghousahmed i have already someone working on this

**Comment by sbahaddi** [comment]
i started working on it.

**Comment by MenoIy** [comment]
@ghousahmed  feel free to to check the code and create an issue  if you see something wrong
live demo  : https://naughty-torvalds-0b0323.netlify.app/
